### PR TITLE
replace snowpack with static server

### PR DESCRIPTION
**Pull request by gr2m**
As I understand it, the only reason you used snowpack was the import of the `dts.json` file.

This pull request replaces the `dts.json` file with a native `dts.js` ES Module, that can be directly imported without any proxy necessary.
It removes `snowpack` and adds [`serve`](https://github.com/vercel/serve) instead

### CODE REVIEW

**Comment by gr2m** [comment]
I think with that change you could just active GitHub pages for this repository, and use the repository root as the pages root?

**Comment by orta** [comment]
Yeah, I was just being lazy with snowpack - let's see if that works

**Comment by orta** [comment]
Confirmed, http://orta.io/octokit-playground/

**Comment by gr2m** [comment]
This is so dope, I can't thank you enough Orta!

I'm trying to add this to a thing I'm building right now. It's mostly static HTML/CSS/JS.

But the content I want it to be initialized with is ignored, instead I see this

image

Do you have any idea what could cause it, or how to debug it?

**Comment by orta** [comment]
Hah, nope, no idea - file encoding maybe?

**Pull request merged**
